<h1>Lab 7: Constraint Satisfaction Problems</h1>

In this lab assignment, we are solving the map coloring problem and crypto-arithmetic problem using constraint satisfaction problem.

In [15]:
# Variables and Data Types
message = "Hello, World!"  # String
number = 42  # Integer
decimal = 3.14  # Float
is_true = True  # Boolean
fruits = ["apple", "banana", "cherry"]  # List (ordered collection)
person = {"name": "Alice", "age": 30, "city": "New York"}  # Dictionary (unordered key-value pairs)

# Printing Output
print(message)
print(number)
print(decimal)
print(is_true)
print("Fruits:", fruits)
print("Person:", person)

# Operators
sum = number + decimal
difference = number - decimal
product = number * decimal
quotient = number / decimal  # Division (results in a float)
floor_division = number // decimal  # Floor division (integer result)
remainder = number % decimal  # Modulo operator (remainder)

print("Sum:", sum)
print("Difference:", difference)
print("Product:", product)
print("Quotient:", quotient)
print("Floor Division:", floor_division)
print("Remainder:", remainder)

# Conditional Statements
if number > decimal:
  print(number, "is greater than", decimal)
elif number == decimal:
  print(number, "is equal to", decimal)
else:
  print(number, "is less than", decimal)

# Loops
for fruit in fruits:  # Looping through each item in a list
  print("Fruit:", fruit)

# Functions (Reusable blocks of code)
def greet(name):
  """
  Greets the user by name.

  Args:
      name: The name of the person to greet (string).
  """
  print("Hello,", name)

greet("Bob")

# Comments (Lines ignored by Python)
# This line is a comment

Hello, World!
42
3.14
True
Fruits: ['apple', 'banana', 'cherry']
Person: {'name': 'Alice', 'age': 30, 'city': 'New York'}
Sum: 45.14
Difference: 38.86
Product: 131.88
Quotient: 13.375796178343949
Floor Division: 13.0
Remainder: 1.1799999999999984
42 is greater than 3.14
Fruit: apple
Fruit: banana
Fruit: cherry
Hello, Bob


In [16]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Print the array
print("Array:", arr)

# Array shape (dimensions)
print("Array shape:", arr.shape)

# Array data type
print("Array data type:", arr.dtype)

# Mathematical operations (element-wise)
sum_arr = arr + 10
print("Add 10 to all elements:", sum_arr)

# Create a multidimensional array (matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:", matrix)

Array: [1 2 3 4 5]
Array shape: (5,)
Array data type: int32
Add 10 to all elements: [11 12 13 14 15]
Matrix: [[1 2 3]
 [4 5 6]]


In [17]:
import pandas as pd

# Create a list of data
data = ["apple", "banana", "cherry", "orange", "mango"]

# Create a Pandas Series (one-dimensional labeled data)
fruits_series = pd.Series(data)
print("Fruits Series:", fruits_series)

# Create a DataFrame (two-dimensional labeled data)
data = {
    "fruits": ["apple", "banana", "cherry"],
    "colors": ["red", "yellow", "red"]
}
df = pd.DataFrame(data)
print("Fruits DataFrame:", df)

# Access elements by index or label
print("First row:", df.iloc[0])  # Access by row index
print("Fruits column:", df["fruits"])  # Access by column name

Fruits Series: 0     apple
1    banana
2    cherry
3    orange
4     mango
dtype: object
Fruits DataFrame:    fruits  colors
0   apple     red
1  banana  yellow
2  cherry     red
First row: fruits    apple
colors      red
Name: 0, dtype: object
Fruits column: 0     apple
1    banana
2    cherry
Name: fruits, dtype: object


In [20]:
def knapsack_brute_force(weights, values, capacity):
  """
  Solves the 0/1 Knapsack Problem using a brute-force approach.

  Args:
      weights: A list of weights for each item (integers).
      values: A list of values for each item (integers).
      capacity: The maximum weight the knapsack can hold (integer).

  Returns:
      A tuple containing the maximum value and the corresponding list of selected items.
  """
  n = len(weights)  # Number of items
  max_value = 0
  best_items = []

  # Iterate through all possible subsets of items (2^n combinations)
  for i in range(2**n):
    current_weight = 0
    current_value = 0
    selected_items_subset = []
    for j in range(n):
      # Check if jth bit is set in the binary representation of i
      if (i >> j) & 1:
        current_weight += weights[j]
        current_value += values[j]
        selected_items_subset.append(j)

    # If the current subset doesn't exceed capacity and has a higher value, update best
    if current_weight <= capacity and current_value > max_value:
      max_value = current_value
      best_items = selected_items_subset

  return max_value, best_items

# Example usage
weights = [2, 3, 1, 4]
values = [4, 5, 3, 7]
capacity = 6

max_value, selected_items = knapsack_brute_force(weights, values, capacity)

print("Maximum value:", max_value)
print("Selected items:")
for i in selected_items:
    print( weights[i], end=' ')

Maximum value: 12
Selected items:
2 3 1 

In [14]:
import numpy as np

# Vector creation
vector_row = np.array([1, 2, 3])  # Row vector
vector_col = np.array([[1], [2], [3]])  # Column vector

# Matrix creation
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

# Vector operations
vector_sum = vector_row + vector_row  # Element-wise addition
vector_diff = vector_col - vector_col  # Element-wise subtraction
vector_dot = np.dot(vector_col.T, vector_row)  # Dot product

# Matrix operations
matrix_sum = matrix_a + matrix_b  # Element-wise addition
matrix_diff = matrix_a - matrix_b  # Element-wise subtraction
matrix_product = np.dot(matrix_a, matrix_b)  # Matrix multiplication

# Other useful operations
matrix_transpose = matrix_a.T  # Transpose
matrix_inverse = np.linalg.inv(matrix_a)  # Inverse (if invertible)
matrix_determinant = np.linalg.det(matrix_a)  # Determinant

# Printing results
print("Vector sum (row + row): \n", vector_sum)
print("Vector difference (col - col): ", )
print(vector_diff)
print("Vector dot product: \n", vector_dot)

print("Matrix sum: \n", matrix_sum)
print("Matrix difference: \n", matrix_diff)
print("Matrix product: \n", matrix_product)
print("Matrix transpose: \n", matrix_transpose)
print("Matrix inverse: \n", matrix_inverse)  # Assuming matrix_a is invertible
print("Matrix determinant: \n", matrix_determinant)

Vector sum (row + row): 
 [2 4 6]
Vector difference (col - col): 
[[0]
 [0]
 [0]]
Vector dot product: 
 [14]
Matrix sum: 
 [[ 6  8]
 [10 12]]
Matrix difference: 
 [[-4 -4]
 [-4 -4]]
Matrix product: 
 [[19 22]
 [43 50]]
Matrix transpose: 
 [[1 3]
 [2 4]]
Matrix inverse: 
 [[-2.   1. ]
 [ 1.5 -0.5]]
Matrix determinant: 
 -2.0000000000000004


In [1]:
#Import the necessary libraries
from typing import Generic, TypeVar, Dict, List, Optional
from abc import ABC, abstractmethod

#Declares a type variable V as variable type and D as domain type
V = TypeVar('V') # variable type
D = TypeVar('D') # domain type

#This is a Base class for all constraints
class Constraint(Generic[V, D], ABC):
    # The variables that the constraint is between
    def __init__(self, variables: List[V]) -> None:
        self.variables = variables

    # This is an abstract method which must be overridden by subclasses
    @abstractmethod
    def satisfied(self, assignment: Dict[V, D]) -> bool:
        ...


# A constraint satisfaction problem consists of variables of type V
# that have ranges of values known as domains of type D and constraints
# that determine whether a particular variable's domain selection is valid
class CSP(Generic[V, D]):
    def __init__(self, variables: List[V], domains: Dict[V, List[D]]) -> None:
        # variables to be constrained
        # Assign variables parameter to self.variables
        self.variables: List[V] = variables 
        # domain of each variable
        # Assign domains parameter to self.domains
        self.domains: Dict[V, List[D]] = domains
        # Assign an empty dictionary to self.constraints
        self.constraints: Dict[V, List[Constraint[V, D]]] = {}
        # Iterate over self.variables
        for variable in self.variables:
            self.constraints[variable] = []
            #If the variable is not in domains, then raise a LookupError("Every variable should have a domain assigned to it.")
            if variable not in self.domains:
                raise LookupError("Every variable should have a domain assigned to it.")

    #This method add constraint to variables as per their domains 
    def add_constraint(self, constraint: Constraint[V, D]) -> None:
        for variable in constraint.variables:
            if variable not in self.variables:
                raise LookupError("Variable in constraint not in CSP")
            else:
                self.constraints[variable].append(constraint)

    # Check if the value assignment is consistent by checking all constraints
    # for the given variable against it
    def consistent(self, variable: V, assignment: Dict[V, D]) -> bool:
        # Iterate over self.constraints[variable]
        for constraint in self.constraints[variable]:
            # if constraint not satisfied then return False
            if not constraint.satisfied(assignment):
                return False
        # otherwise return True
        return True
    
    #This method is performing the backtracking search to find the result
    def backtracking_search(self, assignment: Dict[V, D] = {}) -> Optional[Dict[V, D]]:
        # assignment is complete if every variable is assigned (our base case)
        if len(assignment) == len(self.variables):
            return assignment

        # get all variables in the CSP but not in the assignment
        unassigned: List[V] = [v for v in self.variables if v not in assignment]

        # get the every possible domain value of the first unassigned variable
        first: V = unassigned[0]
        # Iterate over self.domains[first]
        for value in self.domains[first]:
            local_assignment = assignment.copy()
            # Assign the value
            local_assignment[first] = value
            # if we're still consistent, we recurse (continue)
            if self.consistent(first, local_assignment):
                # recursively call the self.backtracking_search method based on the local_assignment
                result: Optional[Dict[V, D]] = self.backtracking_search(local_assignment)
                # if we didn't find the result, we will end up backtracking
                if result is not None:
                    return result
                
        return None
    
#MapColoringConstraint is a subclass of Constraint class 
class MapColoringConstraint(Constraint[str, str]):
    def __init__(self, place1: str, place2: str) -> None:
        super().__init__([place1, place2])
        self.place1: str = place1
        self.place2: str = place2
    #Define the abstract method satisfied in subclass
    def satisfied(self, assignment: Dict[str, str]) -> bool:
        # If either place is not in the assignment then it is not
        # yet possible for their colors to be conflicting
        if self.place1 not in assignment or self.place2 not in assignment:
            return True
        # check the color assigned to place1 is not the same as the
        # color assigned to place2
        return assignment[self.place1] != assignment[self.place2]
    

#Main starts
if __name__ == "__main__":
    #Initializes the variables as per the regions of the graph
    variables: List[str] = ["BOX_1", "BOX_2", "BOX_4",
                            "BOX_3", "BOX_5", "BOX_6", "BOX_7"]
    # Initialize the domain as empty dictionary 
    domains: Dict[str, List[str]] = {}

    for variable in variables:
        #Initialize the domain of each variable
        domains[variable] = ["red", "green", "blue"]

    #Instantiate the object of CSP
    csp: CSP[str, str] = CSP(variables, domains)
    #Add constraints to the given MAP problem
    csp.add_constraint(MapColoringConstraint("BOX_1", "BOX_2"))
    csp.add_constraint(MapColoringConstraint("BOX_1", "BOX_4"))
    csp.add_constraint(MapColoringConstraint("BOX_4", "BOX_2"))
    csp.add_constraint(MapColoringConstraint("BOX_3", "BOX_2"))
    csp.add_constraint(MapColoringConstraint("BOX_3", "BOX_4"))
    csp.add_constraint(MapColoringConstraint("BOX_3", "BOX_5"))
    csp.add_constraint(MapColoringConstraint("BOX_5", "BOX_4"))
    csp.add_constraint(MapColoringConstraint("BOX_6", "BOX_4"))
    csp.add_constraint(MapColoringConstraint("BOX_6", "BOX_5"))
    csp.add_constraint(MapColoringConstraint("BOX_6", "BOX_7"))
    #Finding the solution to the problem by calling the backtracking_search() method
    solution: Optional[Dict[str, str]] = csp.backtracking_search()
    if solution is None:
        print("No solution found!")
    else:
        print(solution)



#SendMoreMoneyConstraint is a subclass of Constraint class
class SendMoreMoneyConstraint(Constraint[str, int]):
    def __init__(self, letters: List[str]) -> None:
        super().__init__(letters)
        self.letters: List[str] = letters

    def satisfied(self, assignment: Dict[str, int]) -> bool:
        # if there are duplicate values then it's not a solution
        if len(set(assignment.values())) < len(assignment):
            return False

        # if all variables have been assigned, check if it adds correctly
        if len(assignment) == len(self.letters):
            s: int = assignment["S"]
            e: int = assignment["E"]
            n: int = assignment["N"]
            d: int = assignment["D"]
            m: int = assignment["M"]
            o: int = assignment["O"]
            r: int = assignment["R"]
            y: int = assignment["Y"]
            send: int = s * 1000 + e * 100 + n * 10 + d
            more: int = m * 1000 + o * 100 + r * 10 + e
            money: int = m * 10000 + o * 1000 + n * 100 + e * 10 + y
            return send + more == money
        return True # no conflict
    

if __name__ == "__main__":
    letters: List[str] = ["S", "E", "N", "D", "M", "O", "R", "Y"]
    possible_digits: Dict[str, List[int]] = {}
    for letter in letters:
        possible_digits[letter] = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    possible_digits["M"] = [1]  # so we don't get answers starting with a 0
    csp: CSP[str, int] = CSP(letters, possible_digits)
    csp.add_constraint(SendMoreMoneyConstraint(letters))
    solution: Optional[Dict[str, int]] = csp.backtracking_search()
    if solution is None:
        print("No solution found!")
    else:
        print(solution)

{'BOX_1': 'red', 'BOX_2': 'green', 'BOX_4': 'blue', 'BOX_3': 'red', 'BOX_5': 'green', 'BOX_6': 'red', 'BOX_7': 'green'}


{'S': 9, 'E': 5, 'N': 6, 'D': 7, 'M': 1, 'O': 0, 'R': 8, 'Y': 2}
